name: Build Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/bun-action@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun build
