name: Doc Svelte Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/doc/src/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: apps/doc
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check Svelte
        run: bun check
