name: Format Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/cliparoo/**'

defaults:
  run:
    working-directory: apps/cliparoo

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting
        run: bun format:check
