name: Svelte Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/cliparoo/src/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/cliparoo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check Svelte
        run: bun check
